### ISSUE TITLE
Chrome 67 - Breaks back / forward history

### ISSUE THREAD

**Issue by r-a-y** [aghorler/History-Disabler-for-Chromium#1]
Hi, I've been using this extension for a long time and it's been working great!

Just upgraded to Chrome 67 and when browsing more than one page, the back and forward history is also purged.  This makes it impossible to navigate a tab's history with the back and forward toolbar buttons.

Let me know if you need any more details from me.

**Comment by aghorler** [comment]
Hi @r-a-y , I cannot reproduce this on `67.0.3396.62`.

Can you more specifically describe what you're doing, and how the extension makes Chrome behave?

Thanks.

**Comment by r-a-y** [comment]
Hmm, it looks like it's working again.

If the problem comes up again, I'll try to recreate the issue and reopen with details.

**Comment by aghorler** [comment]
I'm reopening this because someone else emailed me about this issue, and I _think_ I've seen it in my normal browsing. It almost seems random. 

I will investigate further.

**Comment by aghorler** [comment]
Okay. I can confirm that this is a bug. It appears that Chrome's back and forward navigation functionality now (from version 67) depends on history. The reason that this bug is so occasional must be a timing issue.

I'm currently working on a new release of History Disabler that will restore back/forward functionality by retaining history for a tab until it is closed.

**Comment by tdw80** [comment]
I have the same issue.
Happens in YouTube...
I choose a video -> back button still enabled.
YouTube auto plays the next video -> back button disabled.

**Comment by aghorler** [comment]
If possible, can anyone reading this test the [alpha 2.0.0 release](https://github.com/aghorler/History-Disabler-for-Chromium/releases/tag/2.0.0-alpha) of History Disabler. It aims to resolve this issue by retaining a tabs history until that tab is closed.

**Comment by r-a-y** [comment]
Thanks for your work on this, aghorler.

I'm testing the alpha and will let you know if I encounter the problem in the next couple of days.

**Comment by r-a-y** [comment]
I've been testing this a bit and the alpha doesn't appear to clear pages correctly.

I added some debug statements to the onRemoved listener and it doesn't appear to fire consistently.  Not sure why.

**Comment by PeppeL-G** [comment]
I used [No History](https://chrome.google.com/webstore/detail/no-history/ljamgkbcojbnmcaonjokopmcblmmpfch?hl=en) before, and they got the same problem. I've been playing with this a bit myself, and my observations so far:

- `chrome.browsingData.removeHistory()` also changes back/forward history.
- `chrome.history.deleteUrl()` does not change back/forward history.

**Comment by aghorler** [comment]
@PeppeL-G In my testing both APIs cause issues with back/forward history. No History uses `chrome.history.deleteUrl()`.

@r-a-y It appears that the onRemoved listener is fired consistently. For some reason, Chrome isn't iterating through the arrays in some cases. I think this may be a limitation of some sort.

I'll continue to work on this. I'm just limited to only working on weekends due to time restrictions.

**Comment by aghorler** [comment]
Okay. The issue was caused by me using `array.splice()` to clear indexes from the history log. I've fixed this in [alpha release 2.0.1](https://github.com/aghorler/History-Disabler-for-Chromium/releases/tag/2.0.1-alpha).

**Comment by tomasz1986** [comment]
I have the same issue. Thank you very much for the quick fix. I have just installed the alpha version and will let you know if the problem still persists.

**Comment by PeppeL-G** [comment]
I've only tested alpha 2.0.1 for five minutes, but it seem to work as expected. However, I'm only ~95% satisfied with "retaining a tabs history until that tab is closed". The reason I want to use an extension like this is to get the omnibox to *only suggest bookmarks, and not words I've searched for before*. Do you know if there exists a better solution for me?

**Comment by r-a-y** [comment]
Unfortunately, I can't confirm PeppeL-G's report.  When testing 2.0.1, I'm still experiencing the same problem as I noted before -- the `onRemoved` listener doesn't appear to fire.

I put a `console.log( tabs );` call right after:
https://github.com/aghorler/History-Disabler-for-Chromium/blob/master/js/background.js#L47

And the debug message doesn't fire.  I'm not seeing any `clearing URL` console log message.

I'm getting plenty of `added URL to index X` and `created and added URL to index X` messages though.

Tested on Chromium `67.0.3396.87`, bit I have a bunch of extensions enabled.  I might try on a fresh install later on in the week.

For now, I've started using History AutoDelete and while that works, you can still view older URLs under the 3 dot menu and clicking on History.

**Comment by aghorler** [comment]
@PeppeL-G I agree. It's annoying, but if the inbuilt back/forward navigation functionality depend on history - there may be no other solution.

@r-a-y I'd definitely try with a fresh profile. You could have another extension that is somehow(?) affecting the listener.

Someone emailed me saying [this extension](https://chrome.google.com/webstore/detail/shhh-history-blocker/jnmmnoofehhdegjggelhimkbjgcbbggc) works. It's using the same API, but clearing slightly differently (by date range rather than URL). Can some of you test it? I've checked the source and it's safe.

**Comment by Nuieve** [comment]
Another person here reporting back button not working anymore. Looking forward for a fix...

**Comment by aghorler** [comment]
I'm ready to push the latest alpha live. It's not perfect, but I'm unable to find a perfect solution with the API offered by Chrome.

**Comment by tomasz1986** [comment]
The alpha version seems to work fine when it comes to clearing history and preserving back / forward functionality. I think that there may be a problem with reopening closed tabs though. Using Ctrl + Shift + t does not restore the recently closed tab but a much older one. It seems to restore tabs starting from those closed first and going forward through the history. Has anyone else got this issue?

**Comment by aghorler** [comment]
I've just published release 2.0.2 in the Chrome Web Store.

**Comment by aghorler** [comment]
I'm going to have to build legacy functionality (with an option to switch between deleting history as it's created and when tabs are closed) as users have been reporting the extension as non-functional, and Google has now taken it down.

**Comment by PeppeL-G** [comment]
O.o Chrome is an evergreen browser, why do people use old versions?

For Android applications, it's possible to set "min version" of Android the application works on. Not possible to do something similar with chrome extensions? Would be a simple solution.

**Comment by aghorler** [comment]
@PeppeL-G You can specify a minimum version in the manifest. But I don't think that's the issue.

I think I failed to communicate the changes to the user base - so some of them complained to Google thinking the extension was nonfunctional.

I've just released version `2.1.0`. This version adds the ability to revert back to the old method of disabling history (despite its recent issues), and automatically opens the options page on installation and (for just this release) update. 

This will hopefully communicate the change to users.
